### ISSUE TITLE
Make logging report crawling 'i of n' pages at INFO level

### ISSUE THREAD

**Issue by justinccdev** [buzzbangorg/bsbang-crawler-ng#5]
Currently, the log reports extraction and database add of every page.  Can we drop the 'add' message (report only on failure) and make the log messages report only every 100 pages or so of the total, if we know it? For example

```
INFO: Extracted 300 of 4000000 pages (last page https://www.ebi.ac.uk/biosamples/samples/SAMEA2381639)
```

Similar to the existing scraper.  I'm not sure if Scrapy will know the total number of pages beforehand (i.e. if it takes the same approach as the old scraper of gathering all URLs first before inspecting them), but it will be great to have this number to set user expectations of how long the process will take.

**Comment by justinccdev** [comment]
Ahh, in fact looking at the output, I see now there are regular 

```
[scrapy.extensions.logstats] INFO: Crawled 81512 pages (at 4957 pages/min), scraped 81843 items (at 4597 items/min) like messages
```

though those don't give the total to crawl.

**Comment by innovationchef** [comment]
Since Scrapy works asynchronously and it crawls down as it keeps finding new URLs, it is not possible to show the progress of scraping in [i of n] format. However, I think this feature is important as it gives the users some sense of the progress. Therefore I want to suggest an approach, which will not give the precise result, but some sense of progress. 

I enlisted the URLs in the base sitemap.xml file before starting the Scrapy engine and stored them in a dictionary with URL(as keys) and visit_flag(as values) to track down how many pages have already been reached. This method is not precise as the sitemaps and nested and I have tracked down the visit of only the 1st layer of the sitemap. But, this appears to be fine. What do you think about it? "
 [Code](https://github.com/buzzbangorg/bsbang-crawler-ng/commit/e001541342ade99e110f829914fb78b546bccde5)

**Comment by justinccdev** [comment]
Yeah, I think logging that gives just some sense is still useful and absolutely fine.
